library(ri)
library(wfe)

setwd("/media/minh/Dropbox (MIT)/Documents/Works/Vietnam Elections/Data/Working Data")
#setwd("D:/Dropbox (MIT)/Documents/Works/Vietnam Elections/Data/Working Data")
#setwd("C:/Users/Nga Nguy/Dropbox (MIT)/Documents/Works/Vietnam Elections/Data/Working Data")

source("../../Code/Spring 2018/Merge_All.R")

#######

## 28 Feb 2018 update: instead of factoring out num.candidates and num.elected, we now use variables that indicate
## number of easy districts
## 28 Feb 2018 update: use net.trans as DV and control for net.trans.lag instead of the log difference

## 08 Mar 2018 update: updated vietnamdata package so that RI regression functions can accept user-input
## permutation matrix (i.e. as generated by ri::genperms)
## 08 Mar 2018 update: discovered that vietnamdata::genperms produce too many duplicates for most cases, also
## produce wrong permutation (treatment even for non-election year) in many cases when using clus="period.prov"
## so generating all permutation with ri::genperms now
## 08 Mar 2018 update: reorganized the code so that, for each set of election, a dataset is created separately,
## and then a permutation matrix, instead of having everything in function calls. Also saving output objects

## 16 Mar 2018 update: modified ri::rireg and ri::riwfe to restrict set of eligible permutation to those
## that (fuzzy) matches Z'X = D'X where Z is the original treatment vector and D is the permuted treatment
## vector. Implemented two methods: exact match, when only treatment vectors D s.t. Z'X = D'X are permited, and
## fuzzy match, when treatment vectors D s.t. Z'X and D'X are "close enough" are permitted, where closeness
## is being defined by a distance metric (default is Euclidean) and enough is defined by a threshold parameter
## (default is the 10 percentile of all the distances).

## 21 Mar 2018 update: modified every regression such that the outcome variable is now net.trans.log.change
## i.e. first-differenced outcome to fit a Dif-in-Dif-in-Dif framework. In addition, add into covariates 
## defeat.2007, defeat.2011, defeat.2016 to be an indicator for ever being treated at all. Both additions
## match the math derived on 21 Mar 2018, which shows how the DiDiD framework can be fitted using
## first differenced outcome. Under this new specification, result for 2007 and 2011 are solidly null
## whereas result for 2016 is solidly positive regardless of whether we are using Fisher or Neyman inference.

## If we ever want to revert to normal Dif-in-Dif framework i.e. using net.trans as the outcome, revert back to
## 16 Mar 2018 version using Dropbox

## 21 Mar 2018 update #2: modified Clean_Budget to add additional variables. Most notable are X.log.change
## and X.change.log. In particular: X.log.change is the change in log scale i.e. log(X_t) - log(X_t-1);
## X.change.log is the log of the change i.e. log(X_t = X_t-1). Also modified the outcome variable to be
## specifically net.trans.log.change i.e. change in log scale, based on a model that at the basic level
## log(net.trans) is determined by the treatment. For control, testing different controls, but so far
## total.rev.log.change.lag i.e. change in log scale of past and past2 total revenue i.e.
## log(X_t-1) - log(X_t-2) yields almost no significant results

## 21 Mar 2018 update #3: Regressions seem to only work when DV is net.trans.change.log i.e. log of the
## difference. Appropriate control seems to be net.trans.lag, which is not a first-differenced variable.
## Not sure how this squares up with the math that I derived. Also created an "ever.defeat" variable
## to use with pooled panels instead of having separate indicators for ever being defeated in each of the
## three election years

## TO DO: For DiDiD framework, the specification calls for covariates to enter also as first-differenced.
## Things seem to work for num.candidates etc. since the first-differenced version is identical.
## But for net.trans.lag, it's harder to tell. Need to think more carefully about whether to use
## a first differenced net.trans.log.change.lag (dif of two logs), a net.trans.change.log.lag (log of dif), or
## a normal total.rev.log.change.lag (if we think total.rev.log.change.lag determines treatment -- but even then maybe
## first differenced total.rev.log.change.lag may still be better)

## TO DO: think more carefully about principled ways to define closeness and choose appropriate threshold parameter
## Also need to check whether standardizing covariates before calculating Z'X is a good idea (I think it is).
## So far, setting threshold at 10th percentile results in (perhaps) more permuted vectors than necessary;
## but dropping threshold lower makes p-values look pretty bad... probably because lower threshold means that
## many permutations get dropped, and these permutations are likely to form the middle part of the distribution

## One-year change, cross-sectional regression
## NOTE: ignore these results at the end of the day

# 2007
dat_2007_c <- plan %>%
  group_by(prov) %>%
  mutate(net.trans.change.log.lag = lag(net.trans.change.log, order_by = year)) %>%
  filter(year==2008) %>%
  filter(defeat.2007!=0 | closewin.2007!=0) %>%
  filter(prov!="Ha Noi" & prov!="TP HCM")
perm_2007_c <- ri::genperms(dat_2007_c$defeat)

lm_2007_c <- lm(net.trans.change.log ~ defeat.2007 + net.trans.lag + num.districts + num.districts.5 + num.candidates + num.centralnominees,
                data = dat_2007_c) # just lm
lfe_2007_c <- rireg(data = dat_2007_c,
                    outcome = "net.trans.change.log",
                    treatment = "defeat.2007",
                    covs = c("net.trans.lag", "num.districts", "num.districts.5", "num.candidates", "num.centralnominees"),
                    perm = perm_2007_c) # lm under RI

summary(lm_2007_c)
lfe_2007_c

# 2011
dat_2011_c <- plan %>%
  mutate(net.trans.change.log.lag = lag(net.trans.change.log, order_by = year)) %>%
  filter(year==2012) %>%
  filter(defeat.2011!=0 | closewin.2011!=0) %>%
  filter(prov!="Ha Noi" & prov!="TP HCM")
perm_2011_c <- ri::genperms(dat_2011_c$defeat)

lm_2011_c <- lm(net.trans.change.log ~ defeat.2011 + net.trans.lag + num.districts + num.districts.5 + num.candidates + num.centralnominees,
                data = dat_2011_c) # just lm
lfe_2011_c <- rireg(data = dat_2011_c,
                    outcome = "net.trans.change.log",
                    treatment = "defeat.2011",
                    covs = c("net.trans.lag", "num.districts", "num.districts.5", "num.candidates", "num.centralnominees"),
                    perm = perm_2011_c) # lm under RI

summary(lm_2011_c)
lfe_2011_c


# 2016
dat_2016_c <- plan %>%
  mutate(net.trans.change.log.lag = lag(net.trans.change.log, order_by = year)) %>%
  filter(year==2017) %>%
  filter(defeat.2016!=0 | closewin.2016!=0) %>%
  filter(prov!="Ha Noi" & prov!="TP HCM")
perm_2016_c <- ri::genperms(dat_2016_c$defeat)

lm_2016_c <- lm(net.trans.change.log ~ defeat.2016 + net.trans.lag + num.districts + num.districts.5 + num.candidates + num.centralnominees,
                data = dat_2016_c) # just lm
lfe_2016_c <- rireg(data = dat_2016_c,
                    outcome = "net.trans.change.log",
                    treatment = "defeat.2016",
                    covs = c("net.trans.lag", "num.districts", "num.districts.5", "num.candidates", "num.centralnominees"),
                    perm = perm_2016_c) # lm under RI

summary(lm_2016_c)
lfe_2016_c


## One-year change, linear fixed effects panel regression

# all three elections in one regression
dat_all_1 <- plan %>%
  mutate(net.trans.change.log.lag = lag(net.trans.change.log, order_by = year)) %>%
  mutate(ever.defeat = as.numeric(defeat.2007 == 1 | defeat.2011 == 1 | defeat.2016 == 1)) %>%
  filter(defeat.2007!=0 | closewin.2007!=0 | defeat.2011!=0 | closewin.2011!=0 | defeat.2016!=0 | closewin.2016!=0) %>%
  filter(prov!="Ha Noi" & prov!="TP HCM") %>%
  filter(!is.na(net.trans.change.log.lag))
perm_all_1 <- ri::genperms(dat_all_1$defeat, block = dat_all_1$year)

lm_all_1 <- lm(net.trans.change.log ~ defeat + ever.defeat + net.trans.lag + num.districts + num.districts.5 + num.candidates + num.centralnominees +
                 factor(prov) + factor(year),
               data = dat_all_1) # just lm
lfe_all_1 <- rireg(data = dat_all_1,
                   outcome = "net.trans.change.log",
                   treatment = "defeat",
                   covs = c("net.trans.lag", 
                            "ever.defeat",
                            "num.districts", "num.districts.5", "num.candidates", "num.centralnominees", "factor(prov)", "factor(year)"),
                   perm = perm_all_1) # lm under RI

summary(lm_all_1)
lfe_all_1

# 2007
dat_2007_1 <- plan %>%
  mutate(net.trans.change.log.lag = lag(net.trans.change.log, order_by = year)) %>%
  mutate(defeat = defeat.2007*as.numeric(year==2008)) %>%
  mutate_at(vars(num.districts:num.closewin), funs(. * as.numeric(year==2008))) %>%
  filter(year < 2009) %>% # avoid post-treatment
  filter(defeat.2007!=0 | closewin.2007!=0) %>%
  filter(prov!="Ha Noi" & prov!="TP HCM") %>%
  filter(!is.na(net.trans.change.log.lag))
perm_2007_1 <- ri::genperms(dat_2007_1$defeat, block = dat_2007_1$year)

lm_2007_1 <- lm(net.trans.change.log ~ defeat + defeat.2007 + net.trans.lag + num.districts + num.districts.5 + num.candidates + num.centralnominees +
                  factor(prov) + factor(year),
                data = dat_2007_1) # just lm
lfe_2007_1 <- rireg(data = dat_2007_1,
                    outcome = "net.trans.change.log",
                    treatment = "defeat",
                    covs = c("net.trans.lag", "defeat.2007", "num.districts", "num.districts.5", "num.candidates", "num.centralnominees", "factor(prov)", "factor(year)"),
                    perm = perm_2007_1) # lm under RI

summary(lm_2007_1)
lfe_2007_1

# 2011 election only
dat_2011_1 <- plan %>%
  mutate(net.trans.change.log.lag = lag(net.trans.change.log, order_by = year)) %>%
  mutate(defeat = defeat.2011*as.numeric(year==2012)) %>%
  mutate_at(vars(num.districts:num.closewin), funs(. * as.numeric(year==2012))) %>%
  filter(year < 2013 & year > 2008) %>% # avoid post-treatment
  filter(defeat.2011!=0 | closewin.2011!=0) %>%
  filter(prov!="Ha Noi" & prov!="TP HCM") %>%
  filter(!is.na(net.trans.change.log.lag))
perm_2011_1 <- ri::genperms(dat_2011_1$defeat, block = dat_2011_1$year, maxiter = 20000)

lm_2011_1 <- lm(net.trans.change.log ~ defeat + defeat.2011 + net.trans.lag + num.districts + num.districts.5 + num.candidates + num.centralnominees +
                  factor(prov) + factor(year),
                data = dat_2011_1) # just lm
lfe_2011_1 <- rireg(data = dat_2011_1,
                    outcome = "net.trans.change.log",
                    treatment = "defeat",
                    covs = c("net.trans.lag", "defeat.2011", "num.districts", "num.districts.5", "num.candidates", "num.centralnominees", "factor(prov)", "factor(year)"),
                    perm = perm_2011_1) # lm under RI

summary(lm_2011_1)
lfe_2011_1

# 2016 election only
dat_2016_1 <- plan %>%
  mutate(net.trans.change.log.lag = lag(net.trans.change.log, order_by = year)) %>%
  mutate(defeat = defeat.2016*as.numeric(year==2017)) %>%
  mutate_at(vars(num.districts:num.closewin), funs(. * as.numeric(year==2017))) %>%
  filter(year < 2018 & year > 2012) %>% # avoid post-treatment
  filter(defeat.2016!=0 | closewin.2016!=0) %>%
  filter(prov!="Ha Noi" & prov!="TP HCM") %>%
  filter(!is.na(net.trans.change.log.lag))
perm_2016_1 <- ri::genperms(dat_2016_1$defeat, block = dat_2016_1$year, maxiter = 20000)

lm_2016_1 <- lm(net.trans.change.log ~ defeat + defeat.2016 + net.trans.lag + num.districts + num.districts.5 + num.candidates + num.centralnominees +
                  factor(prov) + factor(year),
                data = dat_2016_1) # just lm
lfe_2016_1 <- rireg(data = dat_2016_1,
                    outcome = "net.trans.change.log",
                    treatment = "defeat",
                    covs = c("net.trans.lag", "defeat.2016", "num.districts", "num.districts.5", "num.candidates", "num.centralnominees", "factor(prov)", "factor(year)"),
                    perm = perm_2016_1) # lm under RI

summary(lm_2016_1)
lfe_2016_1

### So far: result is: null for 2007 and 2011, solid positive for 2016

## persistent change, linear fixed effects panel regression

# all three elections in one regression
dat_all_p <- plan %>%
  mutate(net.trans.change.log.lag = lag(net.trans.change.log, order_by = year)) %>%
  mutate(ever.defeat = as.numeric(defeat.2007 == 1 | defeat.2011 == 1 | defeat.2016 == 1)) %>%
  mutate(period = as.numeric(cut(year, breaks = c(-Inf, 2007, 2011, 2016, Inf), right = T))) %>% ## "filing down" treatment
  mutate(period.prov = as.factor(paste(prov, period))) %>%
  mutate_at(vars(num.districts:num.closewin), funs(ifelse(.==0, NA, .))) %>%
  group_by(prov, period) %>%
  fill(num.districts:num.closewin) %>%
  ungroup %>%
  mutate_at(vars(num.districts:num.closewin), funs(ifelse(is.na(.), 0, .))) %>%
  filter(defeat.2007!=0 | closewin.2007!=0 | defeat.2011!=0 | closewin.2011!=0 | defeat.2016!=0 | closewin.2016!=0) %>%
  filter(prov!="Ha Noi" & prov!="TP HCM") %>%
  filter(!is.na(net.trans.change.log.lag))
perm_all_p <- ri::genperms(dat_all_p$defeat, clus = dat_all_p$period.prov)

lm_all_p <- lm(net.trans.change.log ~ defeat + ever.defeat + net.trans.lag + num.districts + num.districts.5 + num.candidates + num.centralnominees +
             factor(prov) + factor(year),
           data = dat_all_p) # just lm
lfe_all_p <- rireg(data = dat_all_p,
      outcome = "net.trans.change.log",
      treatment = "defeat",
      covs = c("net.trans.lag", 
               "ever.defeat",
               "num.districts", "num.districts.5", "num.candidates", "num.centralnominees", "factor(prov)", "factor(year)"),
      perm = perm_all_p) # lm under RI

summary(lm_all_p)
lfe_all_p

# 2007
dat_2007_p <- plan %>%
  mutate(net.trans.change.log.lag = lag(net.trans.change.log, order_by = year)) %>%
  mutate(period = as.numeric(cut(year, breaks = c(-Inf, 2007, 2011, 2016, Inf), right = T))) %>% ## "filing down" treatment
  mutate(period.prov = as.factor(paste(prov, period))) %>%
  mutate_at(vars(num.districts:num.closewin), funs(ifelse(.==0, NA, .))) %>%
  group_by(prov, period) %>%
  fill(num.districts:num.closewin) %>%
  ungroup %>%
  mutate_at(vars(num.districts:num.closewin), funs(ifelse(is.na(.), 0, .))) %>%
  mutate(defeat = defeat*as.numeric(period==2)) %>%
  mutate_at(vars(num.districts:num.closewin), funs(. * as.numeric(period==2))) %>%
  filter(year < 2011) %>%
  filter(defeat.2007!=0 | closewin.2007!=0) %>%
  filter(prov!="Ha Noi" & prov!="TP HCM") %>%
  filter(!is.na(net.trans.change.log.lag))
perm_2007_p <- ri::genperms(dat_2007_p$defeat, block = dat_2007_p$period, clustvar = dat_2007_p$period.prov)

lm_2007_p <- lm(net.trans.change.log ~ defeat + defeat.2007 + net.trans.lag + num.districts + num.districts.5 + num.candidates + num.centralnominees +
                  factor(prov) + factor(year),
                data = dat_2007_p) # just lm
lfe_2007_p <- rireg(data = dat_2007_p,
                    outcome = "net.trans.change.log",
                    treatment = "defeat",
                    covs = c("net.trans.lag", "defeat.2007", "num.districts", "num.districts.5", "num.candidates", "num.centralnominees", "factor(prov)", "factor(year)"),
                    perm = perm_2007_p) # lm under RI

summary(lm_2007_p)
lfe_2007_p

# 2011
dat_2011_p <- plan %>%
  mutate(net.trans.change.log.lag = lag(net.trans.change.log, order_by = year)) %>%
  mutate(period = as.numeric(cut(year, breaks = c(-Inf, 2007, 2011, 2016, Inf), right = T))) %>% ## "filing down" treatment
  mutate(period.prov = as.factor(paste(prov, period))) %>%
  mutate_at(vars(num.districts:num.closewin), funs(ifelse(.==0, NA, .))) %>%
  group_by(prov, period) %>%
  fill(num.districts:num.closewin) %>%
  ungroup %>%
  mutate_at(vars(num.districts:num.closewin), funs(ifelse(is.na(.), 0, .))) %>%
  mutate(defeat = defeat*as.numeric(period==3)) %>%
  mutate_at(vars(num.districts:num.closewin), funs(. * as.numeric(period==3))) %>%
  filter(year < 2016 & year > 2008) %>%
  filter(defeat.2011!=0 | closewin.2011!=0) %>%
  filter(prov!="Ha Noi" & prov!="TP HCM") %>%
  filter(!is.na(net.trans.change.log.lag))
perm_2011_p <- ri::genperms(dat_2011_p$defeat, block = dat_2011_p$period, clustvar = dat_2011_p$period.prov, maxiter = 20000)

lm_2011_p <- lm(net.trans.change.log ~ defeat + defeat.2011 + net.trans.lag + num.districts + num.districts.5 + num.candidates + num.centralnominees +
                          factor(prov) + factor(year),
                        data = dat_2011_p) # just lm
lfe_2011_p <- rireg(data = dat_2011_p,
      outcome = "net.trans.change.log",
      treatment = "defeat",
      covs = c("net.trans.lag", "defeat.2011", "num.districts", "num.districts.5", "num.candidates", "num.centralnominees", "factor(prov)", "factor(year)"),
      perm = perm_2011_p) # lm under RI

summary(lm_2011_p)
lfe_2011_p

# 2016 -- basically the same as one year change since we have only 1 post-treatment year in data
dat_2016_p <- plan %>%
  mutate(net.trans.change.log.lag = lag(net.trans.change.log, order_by = year)) %>%
  mutate(period = as.numeric(cut(year, breaks = c(-Inf, 2007, 2011, 2016, Inf), right = T))) %>% ## "filing down" treatment
  mutate(period.prov = as.factor(paste(prov, period))) %>%
  mutate_at(vars(num.districts:num.closewin), funs(ifelse(.==0, NA, .))) %>%
  group_by(prov, period) %>%
  fill(num.districts:num.closewin) %>%
  ungroup %>%
  mutate_at(vars(num.districts:num.closewin), funs(ifelse(is.na(.), 0, .))) %>%
  mutate(defeat = defeat*as.numeric(period==4)) %>%
  mutate_at(vars(num.districts:num.closewin), funs(. * as.numeric(period==4))) %>%
  filter(year < 2022 & year > 2012) %>%
  filter(defeat.2016!=0 | closewin.2016!=0) %>%
  filter(prov!="Ha Noi" & prov!="TP HCM") %>%
  filter(!is.na(net.trans.change.log.lag))
perm_2016_p <- ri::genperms(dat_2016_p$defeat, block = dat_2016_p$period, clustvar = dat_2016_p$period.prov)

lm_2016_p <- lm(net.trans.change.log ~ defeat + defeat.2016 + net.trans.lag + num.districts + num.districts.5 + num.candidates + num.centralnominees +
                  factor(prov) + factor(year),
                data = dat_2016_p) # just lm
lfe_2016_p <- rireg(data = dat_2016_p,
      outcome = "net.trans.change.log",
      treatment = "defeat",
      covs = c("net.trans.lag", "defeat.2016", "num.districts", "num.districts.5", "num.candidates", "num.centralnominees", "factor(prov)", "factor(year)"),
      perm = perm_2016_p) # lm under RI

summary(lm_2016_p)
lfe_2016_p

### So far: result is: null for 2007 and 2011, positive for 2016

## One-year change, weighted fixed effects regression

## Doesn't work if including all indicators of ever defeated for 2007, 2011, and 2016

# all three elections in one regression -- cannot do TW fixed effects
dat_all_w1 <- plan %>%
  mutate(net.trans.change.log.lag = lag(net.trans.change.log, order_by = year)) %>%
  mutate(ever.defeat = as.numeric(defeat.2007 == 1 | defeat.2011 == 1 | defeat.2016 == 1)) %>%
  filter(defeat.2007!=0 | closewin.2007!=0 | defeat.2011!=0 | closewin.2011!=0 | defeat.2016!=0 | closewin.2016!=0) %>%
  filter(prov!="Ha Noi" & prov!="TP HCM") %>%
  filter(!is.na(net.trans.change.log.lag))
perm_all_w1 <- ri::genperms(dat_all_w1$defeat, block = dat_all_w1$year)

lm_all_w1 <- wfe(net.trans.change.log ~ defeat + ever.defeat + net.trans.lag + num.districts + num.districts.5 + num.candidates + num.centralnominees,
                 treat = "defeat",
                 unit.index = "prov",
                 time.index = "year",
                 method = "unit",
                 unbiased.se = TRUE,
                 qoi="att",
                 data = dat_all_w1) # run wfe
lfe_all_w1 <- riwfe(data = dat_all_w1,
                    outcome = "net.trans.change.log",
                    treatment = "defeat",
                    covs = c("net.trans.lag", "ever.defeat", "num.districts", "num.districts.5", "num.candidates", "num.centralnominees"),
                    perm = perm_all_w1,
                    unit.index = "prov",
                    time.index = "year",
                    method = "unit",
                    unbiased.se = TRUE,
                    qoi="att") # wfe under RI

summary(lm_all_w1)
lfe_all_w1

## Persistent change, weighted fixed effects regression

# all three elections in one regression
dat_all_wp <- plan %>%
  mutate(net.trans.change.log.lag = lag(net.trans.change.log, order_by = year)) %>%
  mutate(ever.defeat = as.numeric(defeat.2007 == 1 | defeat.2011 == 1 | defeat.2016 == 1)) %>%
  mutate(period = as.numeric(cut(year, breaks = c(-Inf, 2007, 2011, 2016, Inf), right = T))) %>% ## "filing down" treatment
  mutate(period.prov = as.factor(paste(prov, period))) %>%
  mutate_at(vars(num.districts:num.closewin), funs(ifelse(.==0, NA, .))) %>%
  group_by(prov, period) %>%
  fill(num.districts:num.closewin) %>%
  ungroup %>%
  mutate_at(vars(num.districts:num.closewin), funs(ifelse(is.na(.), 0, .))) %>%
  filter(defeat.2007!=0 | closewin.2007!=0 | defeat.2011!=0 | closewin.2011!=0 | defeat.2016!=0 | closewin.2016!=0) %>%
  filter(prov!="Ha Noi" & prov!="TP HCM") %>%
  filter(!is.na(net.trans.change.log.lag))
perm_all_wp <- ri::genperms(dat_all_wp$defeat, block = dat_all_wp$period, clustvar = dat_all_wp$period.prov)

lm_all_wp <- wfe(net.trans.change.log ~ defeat + ever.defeat + net.trans.lag + num.districts + num.districts.5 + num.candidates + num.centralnominees,
                 treat = "defeat",
                 unit.index = "prov",
                 time.index = "year",
                 method = "unit",
                 unbiased.se = TRUE,
                 qoi="att",
                 data = dat_all_wp) # run wfe
lfe_all_wp <- riwfe(data = dat_all_wp,
                  outcome = "net.trans.change.log",
                  treatment = "defeat",
                  covs = c("net.trans.lag", "ever.defeat", "num.districts", "num.districts.5", "num.candidates", "num.centralnominees"),
                  perm = perm_all_wp,
                  unit.index = "prov",
                  time.index = "year",
                  method = "unit",
                  qoi = "att") # wfe under RI

summary(lm_all_wp)
lfe_all_wp

### So far, result for WFE is very strange: clearly significant without RI, but no longer significant with RI
### May need to check RI procedure for WFE as currently I'm doing it in a very hacky way...

### 16 March 2018 Update: Result for WFE is still off: actual beta too far away from permuted betas

### 21 March 2018 Update: Makes sense now; actual beta lies within permuted distribution

### plot main results ###
lay <- rbind(c(NA,1,1,1,2,2,2,3,3,4,4, NA),
             seq(5,16))

gridExtra::grid.arrange(layout_matrix = lay,
                        heights=c(1,10),
                        widths=c(1,rep(3,10), 1),
                        grid::textGrob("Separate Panels, One-year"),
                        grid::textGrob("Separate Panels, Persistent"),
                        grid::textGrob("Pooled Panel, FE"),
                        grid::textGrob("Pooled Panel, WFE"),
                        y.axe(-20,30),
                        plot(lfe_2007_1, scale=F, xmin=-20, xmax=30, title = "2007"),
                        plot(lfe_2011_1, scale=F, xmin=-20, xmax=30, title = "2011"),
                        plot(lfe_2016_1, scale=F, xmin=-20, xmax=30, title = "2016"),
                        plot(lfe_2007_p, scale=F, xmin=-20, xmax=30, title = "2007"),
                        plot(lfe_2011_p, scale=F, xmin=-20, xmax=30, title = "2011"),
                        plot(lfe_2016_p, scale=F, xmin=-20, xmax=30, title = "2016"),
                        plot(lfe_all_1, scale=F, xmin=-20, xmax=30, title = "One-year"),
                        plot(lfe_all_p, scale=F, xmin=-20, xmax=30, title = "Persistent"),
                        plot(lfe_all_w1, scale=F, xmin=-20, xmax=30, title = "One-year"),
                        plot(lfe_all_wp, scale=F, xmin=-20, xmax=30, title = "Persistent"),
                        y.axe(-20,30) + scale_x_continuous(position = "top"))
